/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package org.prashp.lib19;

import java.util.ArrayList;
import java.util.Comparator;

public class EventStream {

    SourceStream source;
    SinkStream sink;

    boolean stop = false;

    long duration;


    public EventStream(SourceStream source, SinkStream sink, long timeWindowMillis) {
        duration = timeWindowMillis;
        this.source = source;
        this.sink = sink;

    }

    /**
     * Sorts events in given stream by version in a given duration
     */
    public void process() {
        //instantiate buffer; will be used to hold events
        ArrayList<Event> buffer = new ArrayList<>();

        //use nanoTime to calculate how much time elapsed.
        long finish = (long) (System.nanoTime() + duration * Math.pow(10,7));
        while(!stop)
        {
            while(finish >= System.nanoTime()) {
                buffer.add(source.getEvent());
            }
            buffer.sort(Comparator.comparingLong(Event::getVersion));

            for (Event e : buffer)
            {
                sink.writeEvent(e);
            }
            buffer = null;

        }

        //sorts by using version

        //writes sorted events to sink stream


    }

    public void stop() {
        this.stop = true;
    }



    public static class Event {
        final long version;
        final long timestamp;
        final Object payload;

        public Event(long version, long timestamp, Object payload) {
            this.version = version;
            this.timestamp = timestamp;
            this.payload = payload;
        }

        public long getVersion() {
            return version;
        }

        public long getTimestamp() {
            return timestamp;
        }

        public Object getPayload() {
            return payload;
        }


    }

}


interface SourceStream {
    EventStream.Event getEvent();
}

interface SinkStream {
    void writeEvent(EventStream.Event e);
}

