/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package org.prashp.lib19;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class LibraryTest {
    @Test void someLibraryMethodReturnsTrue() {
        EventStream classUnderTest = new EventStream(null, null, 10L);
        assertNotNull(classUnderTest);
        Thread.dumpStack();
    }
}
